package com.loongmin4ever.entity;

import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends Model<User> {
	public static final User dao = new User();
}
