package com.loongmin4ever.entity;

import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Whisper extends Model<Whisper> {
	public static final Whisper dao = new Whisper();
}
